import "./globals.css"
import { Open_Sans } from "next/font/google"
import Header from "@/components/Header"
import MobileBottomNav from "@/components/MobileBottomNav"

const open_sans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
})

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={open_sans.style} className="dark:bg-neutral-800">
        <Header />
        <main className="mt-[156px] pb-10 sm:pb-0 mb-[20px] sm:mb-0 max-w-[2360px] xl:mx-auto">
          {children}
        </main>
        <MobileBottomNav />
      </body>
    </html>
  )
}
